# Generated by Django 5.0 on 2023-12-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='id',
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
